name: learnfusion
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.4.4 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  table_calendar: ^3.0.0
  url_launcher: ^6.1.7
  fl_chart: ^0.45.0
  webview_flutter: ^4.0.0
  video_player: ^2.5.1


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/learn_fusion.png
    - assets/images/trends_image.png
    - assets/videos/Workshop.mp4
    - assets/images/workshop.png
    - assets/videos/innov8ers.mp4

    

